default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  # Observação: O Heroku irá SOBRESCREVER essas configurações de produção
  # automaticamente com as credenciais do PostgreSQL que ele mesmo criará.
  # Essa estrutura aqui é apenas para o Rails não reclamar.
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>